name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.1
        env:
          MYSQL_USER: wezvatech
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mywezvadb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      - name: Run Unit Tests
        run: mvn test

      - name: Build Docker image
        run: docker build -t wezvatech-springboot-mysql .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 \
            --link ${{ job.services.db.id }}:db \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mywezvadb \
            wezvatech-springboot-mysql

      - name: Wait for Application to Start
        run: |
          sleep 30
          curl -s http://localhost:8080/actuator/health/liveness | grep UP

      - name: Run Integration Test
        run: curl -X POST -H "Content-Type: application/json" \
          -d '{"title":"Book A", "price":49.99, "publishDate":"2024-04-12"}' \
          "http://localhost:8080/books"
