name: my first workflow 
on: push 

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo 
          uses: actions/checkout@v4
        - name: welcome message 
          run: |
           echo " my first action job"
           ls -lat
           cat README.md
           cowsay -f dragon "Your message here" > output.txt


        # - name: list files
        #   run: ls
         
        # - name: Read file
        #   run: cat README.md  