name: my first workflow 
on: push 

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo 
          uses: actions/checkout@v4
        - name: welcome message 
          run: |
           sudo wget -O /usr/share/cowsay/cows/dog.cow https://example.com/path/to/dog.cow
           sudo nano /usr/share/cowsay/cows/dog.cow
               $the_cow = <<EOC;
               $thoughts
               / \__
              (    @\___
              /         O
             /   (_____/

            

           sudo apt-get reinstall cowsay -y 
           cowsay -f dog "Your message here" > output.txt
           cat output.txt
           echo " my first action job"
           ls -lart
           cat README.md
